2. Update todo (edit and toggle complete)
hhe-wtag/dom-todo pull request #2
Opened 2024-10-10 09:53 UTC by hhe-wtag

2024-10-10 10:01 UTC, hhu-wtag commented
Please update the base brach.

2024-10-13 08:06 UTC, hhu-wtag requested changes

2024-10-13 08:06 UTC, hhu-wtag commented on script.js
Here's my suggestions for the edit workflow:
We'll have some in component state, let's say `isEditing` and `isDone`.

Whenever user clicks on edit button of a todo:
1. Get the id of the todo from the HTML element
2. Find the todo by the id from todos list
3. Toggle, the isEditing to `true`
4. Re-render the whole UI

After this, while creating all the todos, we can have a conditional logic, 
if isEditing:
  showEditState()
else:
  showNormalState()

Same idea goes for done also.

2024-10-13 09:58 UTC, hhe-wtag commented on script.js
I have addressed the changes kindly review

2024-10-13 10:32 UTC, hhu-wtag requested changes

2024-10-13 10:32 UTC, hhu-wtag commented on script.js
> +  );
Too much happening in one line. Let's break it down.

This'll work due to how reference work in JS
```suggestion
  const todo = todos.find(({ id }) => id === todoId)
  
  if(todo === undefined){
    return
  }
  
  todo.isCompleted = !todo.isCompleted
```

2024-10-13 10:32 UTC, hhu-wtag commented on script.js
> +  );
ditto. Please simplify this

2024-10-13 10:32 UTC, hhu-wtag commented on script.js
> +
ditto

2024-10-14 10:29 UTC, hhu-wtag approved these changes

2024-10-14 11:32 UTC, merged